/*
 * Code for class UC_UNICODE_CONSTANTS
 */

#include "eif_eiffel.h"
#include "../E1/estructure.h"


#ifdef __cplusplus
extern "C" {
#endif

extern EIF_TYPED_VALUE F1137_11275(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11276(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11277(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11278(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11279(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11280(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11281(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11282(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11283(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11284(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11285(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11286(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11287(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11288(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11289(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11290(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11291(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11292(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11293(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11294(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11295(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11296(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11297(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11298(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11299(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11300(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11301(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11302(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11303(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11304(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11305(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11306(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11307(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11308(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11309(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11310(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11311(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11312(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11313(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11314(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11315(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11316(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11317(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11318(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11319(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11320(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11321(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11322(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11323(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11324(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11325(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11326(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11327(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11328(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11329(EIF_REFERENCE);
extern EIF_TYPED_VALUE F1137_11330(EIF_REFERENCE);
extern void EIF_Minit1137(void);

#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

/* {UC_UNICODE_CONSTANTS}.minimum_unicode_character_code */
EIF_TYPED_VALUE F1137_11275 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.maximum_unicode_character_code */
EIF_TYPED_VALUE F1137_11276 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1114111L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.minimum_unicode_surrogate_code */
EIF_TYPED_VALUE F1137_11277 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 55296L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.maximum_unicode_surrogate_code */
EIF_TYPED_VALUE F1137_11278 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 57343L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.maximum_bmp_character_code */
EIF_TYPED_VALUE F1137_11279 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 65535L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.minimum_ascii_character_code */
EIF_TYPED_VALUE F1137_11280 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.maximum_ascii_character_code */
EIF_TYPED_VALUE F1137_11281 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 127L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.minimum_ascii_character */
EIF_TYPED_VALUE F1137_11282 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_CHAR8;
	r.it_c1 = (EIF_CHARACTER_8) (EIF_CHARACTER_8) '\000';
	return r;
}

/* {UC_UNICODE_CONSTANTS}.maximum_ascii_character */
EIF_TYPED_VALUE F1137_11283 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_CHAR8;
	r.it_c1 = (EIF_CHARACTER_8) (EIF_CHARACTER_8) '';
	return r;
}

/* {UC_UNICODE_CONSTANTS}.unassigned_other_category */
EIF_TYPED_VALUE F1137_11284 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.uppercase_letter_category */
EIF_TYPED_VALUE F1137_11285 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.lowercase_letter_category */
EIF_TYPED_VALUE F1137_11286 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.titlecase_letter_category */
EIF_TYPED_VALUE F1137_11287 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.modifier_letter_category */
EIF_TYPED_VALUE F1137_11288 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.other_letter_category */
EIF_TYPED_VALUE F1137_11289 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.non_spacing_mark_category */
EIF_TYPED_VALUE F1137_11290 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.spacing_combining_mark_category */
EIF_TYPED_VALUE F1137_11291 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 7L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.enclosing_mark_category */
EIF_TYPED_VALUE F1137_11292 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.decimal_digit_number_category */
EIF_TYPED_VALUE F1137_11293 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 9L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.letter_number_category */
EIF_TYPED_VALUE F1137_11294 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 10L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.other_number_category */
EIF_TYPED_VALUE F1137_11295 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 11L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.connector_punctuation_category */
EIF_TYPED_VALUE F1137_11296 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 12L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.dash_punctuation_category */
EIF_TYPED_VALUE F1137_11297 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 13L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.open_punctuation_category */
EIF_TYPED_VALUE F1137_11298 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 14L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.close_punctuation_category */
EIF_TYPED_VALUE F1137_11299 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 15L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.initial_quote_punctuation_category */
EIF_TYPED_VALUE F1137_11300 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.final_quote_punctuation_category */
EIF_TYPED_VALUE F1137_11301 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 17L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.other_punctuation_category */
EIF_TYPED_VALUE F1137_11302 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 18L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.math_symbol_category */
EIF_TYPED_VALUE F1137_11303 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 19L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.currency_symbol_category */
EIF_TYPED_VALUE F1137_11304 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 20L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.modifier_symbol_category */
EIF_TYPED_VALUE F1137_11305 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 21L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.other_symbol_category */
EIF_TYPED_VALUE F1137_11306 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 22L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.space_separator_category */
EIF_TYPED_VALUE F1137_11307 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 23L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.line_separator_category */
EIF_TYPED_VALUE F1137_11308 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 24L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.paragraph_separator_category */
EIF_TYPED_VALUE F1137_11309 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 25L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.control_other_category */
EIF_TYPED_VALUE F1137_11310 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 26L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.format_other_category */
EIF_TYPED_VALUE F1137_11311 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 27L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.surrogate_other_category */
EIF_TYPED_VALUE F1137_11312 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 28L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.private_other_category */
EIF_TYPED_VALUE F1137_11313 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 29L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.canonical_decomposition_mapping */
EIF_TYPED_VALUE F1137_11314 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.font_decomposition_mapping */
EIF_TYPED_VALUE F1137_11315 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.no_break_decomposition_mapping */
EIF_TYPED_VALUE F1137_11316 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.initial_decomposition_mapping */
EIF_TYPED_VALUE F1137_11317 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.medial_decomposition_mapping */
EIF_TYPED_VALUE F1137_11318 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.final_decomposition_mapping */
EIF_TYPED_VALUE F1137_11319 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.isolated_decomposition_mapping */
EIF_TYPED_VALUE F1137_11320 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.encircled_decomposition_mapping */
EIF_TYPED_VALUE F1137_11321 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 7L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.superscript_decomposition_mapping */
EIF_TYPED_VALUE F1137_11322 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.subscript_decomposition_mapping */
EIF_TYPED_VALUE F1137_11323 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 9L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.vertical_decomposition_mapping */
EIF_TYPED_VALUE F1137_11324 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 10L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.wide_decomposition_mapping */
EIF_TYPED_VALUE F1137_11325 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 11L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.narrow_decomposition_mapping */
EIF_TYPED_VALUE F1137_11326 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 12L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.small_decomposition_mapping */
EIF_TYPED_VALUE F1137_11327 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 13L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.square_decomposition_mapping */
EIF_TYPED_VALUE F1137_11328 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 14L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.fraction_decomposition_mapping */
EIF_TYPED_VALUE F1137_11329 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 15L);
	return r;
}

/* {UC_UNICODE_CONSTANTS}.compatibility_decomposition_mapping */
EIF_TYPED_VALUE F1137_11330 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

void EIF_Minit1137 (void)
{
	GTCX
}


#ifdef __cplusplus
}
#endif
